// app/src/lib/components/Header.svelte
<script>
	import ThemeToggle from './ThemeToggle.svelte';
</script>

<nav
	class="bg-grey-100 text-grey-900 flex justify-between content-center py-6 px-4 md:sticky top-0 z-10 [&>*]:h-min"
>
	<a class="no-underline hover:no-underline transition-none" href="/"
		><h2 class="no-underline text-grey-900 not-italic">How I Made A Game</h2></a
	>
	<div class="flex gap-6 content-center [&>*]:h-min">
		<a class="text-grey-900" href="/#about">About</a>
		<a class="text-grey-900" href="/archive">All Posts</a>
		<a class="text-grey-900" href="/">Home</a>
		<ThemeToggle />
	</div>
</nav>

// app/components/Header.jsx
import Link from 'next/link'

export default function Header() {
    return (
            <div className="header-container">
                <Link href='/' passHref><h2>How I Made A Game</h2></Link>
                <div>
                    <Link href='/#about' passHref>About</Link>
                    <Link href='/archive' passHref>All Posts</Link>
                    <Link href='/' passHref>Home</Link>
                </div>
            </div>
    )
}
