// app/src/lib/components/PostComponent.svelte
<script lang="ts">
	import type { Post } from '$lib/server/post.type';

	export let post: Post;
</script>

<div>
	{post.title}
	<br />
	{post.date}
	<br />
	{post.path}
	<br />
	{post.tags}
	<br />
	{post.excerpt}
	<br />
	<a href={'/blog' + post.path.slice(11).slice(0, -3)}>read</a>
	<hr />
</div>

// app/components/Post.jsx
import Link from 'next/link'

export default function Post({ post }) {
    return (
        <div className='card'>
            <img src={post.frontmatter.cover_image} alt="" />
            <div className="post-date">Posted on {post.frontmatter.date}</div>
            <h3>{post.frontmatter.title}</h3>
            <p>{post.frontmatter.excerpt}</p>
            <Link href={`/blog/${post.slug}`}>
                <a className='btn'>Read More</a>
            </Link>
        </div>
    )
}
